[project]
name = "video-processing-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "librosa>=0.11.0",
    "lxml>=6.0.2",
    "nemo-toolkit[asr]>=2.6.2",
    "numpy>=2.4.2",
    "pydub>=0.25.1",
    "scipy>=1.17.1",
    "torch>=2.9.1",
    "tqdm>=4.67.3",
]
